version: 2.0
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build images
          command: |
            apk update
            apk add build-base
            make
  test:
    working_directory: /app
    docker:
      - image: q0rban/tugboat-baseimage:0.0.2
    steps:
      - checkout
      # Test that Locales are configured correctly.
      - run:
          name: Test locales
          command: |
            set -x
            locale -a | grep ^en_US$
            locale -a | grep ^en_US\.utf8$
      # Test that upstart is diverted to /bin/true.
      # See baseimage/prepare.sh.
      - run:
          name: Test upstart
          command: /sbin/initctl
      # Test that ischroot is diverted to /bin/true.
      # See baseimage/prepare.sh.
      - run:
          name: Test ischroot
          command: /usr/bin/ischroot
      # Test that the cleanup script did what we expect.
      # See baseimage/cleanup.sh
      - run:
          name: Test cleanup
          command: |
            set -x
            ! test -e /bd_build
            # We can't test /tmp because CircleCI puts stuff here.
            #! ls /tmp/* 2>/dev/null
            ! ls /var/tmp/* 2>/dev/null
            ! ls /var/lib/apt/lists/* 2>/dev/null
            ! test -e /etc/dpkg/dpkg.cfg.d/02apt-speedup
            ! ls /etc/ssh/ssh_host_* 2>/dev/null
      # Test the included Makefile.
      - run:
          name: Test Tugboat Makefile
          command: make -C /app/.circleci/test test


workflows:
  version: 2
  test:
    jobs:
      - test
