version: 2.0
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build images
          command: |
            apk update
            apk add build-base
            make
  test-baseimage:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run image tests
          command: |
            apk update
            apk add build-base
            make test-all


workflows:
  version: 2
  test:
    jobs:
      - test-baseimage
