#!/bin/bash

set -e

# We have to start and stop postfix first through init.d to populate
# postfix spool directory for chroot in which postfix is running.
/etc/init.d/postfix start
/etc/init.d/postfix abort

exec /usr/lib/postfix/master -c /etc/postfix -d 2>&1
